import discord.utils
from discord.ext import commands
import os
import random

token = os.getenv('DISCORD_BOT_TOKEN')

intents = discord.Intents.default()
intents.message_content = True
bot = commands.Bot(command_prefix="/", intents=intents)

@bot.event
async def on_ready():
    print("Good morning, in the morning!")

@bot.command()
async def cookie(ctx):
    msg = ctx.message
    await msg.add_reaction("🍪")

@bot.command()
async def fact(ctx):
    facts = [
        "1 byte is 8 bits",
        "Python released February 20, 1991",
        "There are over 700 programming languages",
        "The first computer bug was an actual moth found in a computer in 1947.",
        "The first programming language was created in the 1800s by Ada Lovelace, making her the world’s first programmer.",


    ]
    my_fact = random.choice(facts)
    await ctx.send(my_fact)

@bot.command()
async def about(ctx):
    await ctx.send("I'm Elchin Bot created by E5 on 14.05.2025")

roasts = [
    "You're as useless as the 'g' in lasagna.",
    "If I had a dollar for every smart thing you said, I'd be broke.",
    "You bring everyone so much joy… when you leave the room.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "You have something on your chin… no, the third one down.",
    "Your secrets are always safe with me. I never even listen when you tell me them.",
    "You're not stupid; you just have bad luck thinking.",
    "You're the reason shampoo has instructions.",
    "You're proof that even evolution takes a break sometimes.",
    "You have something on your face: disappointment.",
    "You're the human version of a participation trophy.",
    "Your face makes onions cry.",
    "You are like a software update. Whenever I see you, I think: 'Not now.'",
    "You're like a puzzle with half the pieces missing.",
    "You're the reason they put directions on Pop-Tarts.",
    "You bring everyone together… just to talk about you.",
    "You're like a cloud on a sunny day — not necessary.",
    "You couldn't pour water out of a boot with instructions on the heel.",
    "You're like a speed bump in the highway of life.",
    "You're the result of every bad decision ever made.",
    "You're like a broken pencil — pointless.",
    "You make a sloth look like a sprinter.",
    "You're not dumb — you just have a talent for making bad decisions.",
    "You're like a software bug in human form.",
    "You're the reason they invented the mute button.",
    "You're like a sandwich with no filling.",
    "You're as sharp as a marble.",
    "You bring nothing to the table — not even the table.",
    "You're like a phone with no service — all looks, no use.",
    "You're more disappointing than an unsalted pretzel.",
    "You couldn't find your way out of a paper bag with a map.",
    "You're like expired milk — sour and useless.",
    "You're the kind of person who claps when the plane lands.",
    "You remind me of a cloud: gray and full of hot air.",
    "You’re the reason the gene pool needs a lifeguard.",
    "You're the discount version of someone interesting.",
    "You have something rare: a talent for being annoying.",
    "You're like a calculator with no buttons.",
    "You're so dense, light bends around you.",
    "You're like a dictionary with no definitions.",
    "You're as confusing as a Rubik’s cube in the dark.",
    "You're the loading screen of life — slow and unnecessary.",
    "You're like a web page that never loads.",
    "You're the human version of slow Wi-Fi.",
    "You're like a pop quiz — unwanted and unhelpful.",
    "You're as forgettable as yesterday’s lunch.",
    "You're a few fries short of a Happy Meal.",
    "You're as useful as a screen door on a submarine.",
    "You're like a door with no knob — can’t handle anything.",
    "You're like a coffee cup with no coffee — empty and bitter.",
    "You're the plot twist nobody asked for.",
    "You're like a meme from 2013 — outdated and awkward.",
    "You're the type of person who trips over wireless internet.",
    "You're the kind of person who would lose at solitaire.",
    "You're like a Monday — nobody looks forward to you.",
    "You're the least interesting part of a group project.",
    "You're like a snooze button that doesn’t work.",
    "You're like autocorrect — always messing things up.",
    "You're the leftover pizza no one wants.",
    "You're the human equivalent of a typo.",
    "You're as unnecessary as the 'c' in ‘indict.’",
    "You're as exciting as watching paint dry.",
    "You're like a playlist with only elevator music.",
    "You're like a pencil without lead — can’t make a point.",
    "You're like a lightbulb with no filament.",
    "You're the human version of buffering.",
    "You're about as helpful as a traffic jam.",
    "You're the beta version of a broken app.",
    "You're like a fork in a soup restaurant.",
    "You're like Bluetooth in a dead zone — all show, no go.",
    "You're like a diet soda — tastes like disappointment.",
    "You're like the last slice of bread — dry and unwanted.",
    "You're like a user manual — nobody wants to read you.",
    "You're like a song on loop — annoying after 30 seconds.",
    "You're the reason people check if their mic is muted.",
    "You're a walking Wi-Fi dead zone.",
    "You're the kind of person who makes a mess in Minecraft creative mode.",
    "You're like a fake progress bar — full of lies.",
    "You're like a broken keyboard — can’t type anything smart.",
    "You're the kind of person who brings a spoon to a knife fight.",
    "You're more extra than an unpaid intern.",
    "You're as relevant as MySpace.",
    "You're like a missed call — no one wants to return it.",
    "You're the person who says 'Let's circle back' in a text chat.",
    "You're as welcome as a pop quiz on Friday.",
    "You're like a rejected emoji — unnecessary and confusing.",
    "You're like a bootleg action figure.",
    "You're a low-resolution version of a decent idea.",
    "You're like a banana in a toolbox — weird and unhelpful.",
    "You're like a tab with 47 open sites and no purpose.",
    "You're a search result that didn't help.",
    "You're a software update at 2 AM — inconvenient.",
    "You're the captcha nobody can read.",
    "You're as helpful as a flat tire on a freeway.",
    "You're a demo version of someone better.",
    "You're the ad you skip after 5 seconds.",
    "You're the autocorrect that turns 'homework' into 'homewreck'.",
    "You're the unskippable ad of my life.",
    "You're a background character in your own story.",
    "You're as refreshing as warm soda.",
    "You're the spam folder of friendship.",
    "You're like a pop-up ad — nobody wants you here.",
    "You're like lag in a boss fight.",
    "You're like printer errors — always happening, never helpful.",
    "You're like a knock-knock joke with no punchline.",
    "You're like a GPS that always says 'Recalculating.'",
    "You're like a clickbait title — full of disappointment.",
    "You're the 'before' picture in a tech upgrade.",
    "You're a cold pizza that no one ordered.",
    "You're like subtitles for a silent movie.",
    "You're like a sneeze that never comes.",
    "You're like a USB that never fits the first time.",
    "You're a patch note full of nerfs.",
    "You're like a group chat with 100 unread messages — overwhelming and unimportant.",
    "You're the side quest no one wanted to complete.",
    "You're the reason the tutorial was too long.",
    "You're a CPU with 100% cringe usage.",
    "You're the loading icon that never finishes.",
    "You're like caps lock — accidentally on and annoying.",
    "You're like a Wi-Fi password that’s 48 characters long.",
    "You're the reply guy no one asked for.",
    "You're the lag in every argument.",
    "You're the unnecessary update in a working system.",
    "You're a patch note that broke more things than it fixed.",
    "You're the cooldown no one waits for.",
    "You're like Ctrl+Z in real life — wish you could undo yourself.",
    "You're the error 404 of personality.",
    "You're like a broken download link.",
    "You're the blur on a censored roast.",
    "You're the rejected feature from a beta test.",
    "You're the stock photo of emotions.",
    "You're the autocorrect that ruins a love confession.",
    "You're a plot hole in your own story.",
    "You're the white crayon of the crayon box.",
    "You're the dial-up noise of conversations.",
    "You're like a dark mode without the dark — just empty.",
    "You're the person in group chats who types 'hi' and never responds again.",
    "You're the ‘continue watching?’ message of a boring series.",
    "You're the person who skips the cutscene and doesn’t know the story.",
    "You're the last person anyone would let manage a Minecraft realm.",
    "You're like a potato battery that can’t power a clock.",
    "You're like a hotdog in a smoothie.",
    "You're like a bad mod — always crashing things.",
    "You're the password that doesn’t meet any criteria.",
    "You're like an elevator that stops at every floor… even when no one presses the button.",
    "You're the print button that doesn’t work until the 5th click.",
    "You're like toast in a bath — not a good idea.",
    "You're the mute button that never works in Zoom calls.",
    "You're like a group project — all talk, no contribution.",
    "You're the app that crashes before it loads.",
    "You're a rerun of a show nobody liked the first time.",
    "You're like a keyboard with no space bar — all jammed up.",
    "You're the 'skip intro' button of friendships.",
    "You're the unfunny TikTok on my FYP.",
    "You're like a pencil with no eraser — just mistakes.",
    "You're like a ‘Terms and Conditions’ page — everyone skips you.",
    "You're a delayed reaction in a live stream.",
    "You're like a sneeze in the middle of a speech.",
    "You're the typos in every group chat.",
    "You're the lag spike in real life.",
    "You're like an uncharged controller — looks good, does nothing.",
    "You're like a boot loop — stuck and annoying.",
    "You're the 'I'm not a robot' checkbox that still fails.",
    "You're the final boss of being ignored.",
    "You're like a page that says 'under construction' since 2009.",
    "You're the slow-mo moment no one asked for.",
    "You're the loud chewing in a quiet room.",
    "You're like the last season of a bad TV show — unnecessary.",
    "You're like a tutorial you can't skip.",
    "You're the ad on Spotify that ruins the vibe.",
    "You're the guy who claps when the plane lands — again.",
    "You're like a cat video from 2006 — weirdly low-res and oddly loud.",
    "You're the closed door in an open world.",
    "You're a vibe killer with a driver's license."
]

@bot.command()
async def roast(ctx):
    roast_msg = random.choice(roasts)
    await ctx.send(roast_msg)

bot.run(f"{token}")